os: linux
dist: xenial
language: cpp
compiler: clang
# addons:
  # apt:
    # packages:
    # - libboost-test-dev
    # - libspdlog-dev
script:
- cmake .
- cmake --build .
# - cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -f -T Hw1-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ukuzya0:$BINTRAY_API_KEY "https://api.bintray.com/content/kuzya0/StudyRepo/Homework/$TRAVIS_BUILD_NUMBER/Hw1-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"